# A template must be specified
template: template-starter
default_language: en
languages:
    - en
    - fr
# You can have multiple menus with different names.
# The key for each menu item is the route name, defined in pages.yml
menu:
    main:
        home:
            text: Home
            attributes:
                class: menu-item
        about:
            text: About
            attributes:
                class: menu-item
        contact:
            text: Contact
            attributes:
                class: menu-item
